### ISSUE TITLE
Multiplayer crafting issue

### ISSUE THREAD

**Issue by Guywithissues** [AnonymousHacker1279/ImmersiveWeapons#109]
In singleplayer I can craft gun parts with no issues. But in multiplayer I cant for some reason? Like when I craft and take the trigger assembly out of the small parts table the gold just reappears back and the trigger assembly disappears? The crafting works just fine in singleplayer but not in multiplayer? Pls help.

**Comment by AnonymousHacker1279** [comment]
What version of Immersive Weapons are you using? Additionally, please upload a related `debug.log`.

**Comment by Guywithissues** [comment]
Im using 1.19-1.18.4 and im running it on forge 1.19.2. 
[2023-11-18-2.log.gz](https://github.com/AnonymousHacker1279/ImmersiveWeapons/files/13401868/2023-11-18-2.log.gz)
I dont know anything about logs but I hope this is will help. Also I had a few mods installed with Immersive Weapons so I hope that wont interfere with anything.

**Comment by AnonymousHacker1279** [comment]
This has been confirmed on past versions prior to IW v1.20.0 (MC 1.19.3). The MC 1.19.2 version of Immersive Weapons has been End of Life for a significant period of time. You'll need to update to a newer version for a bugfix.

Unfortunately, I am not capable of managing multiple major versions by myself. If someone else would like to PR a backport with the related fix from [here](https://github.com/AnonymousHacker1279/ImmersiveWeapons/commit/eef423d876483a7c73c1d87dfdaf89875b16ea24), they may do so.
