### ISSUE TITLE
[BUG] Copper Ore not working in Tinker's Construct

### ISSUE THREAD

**Issue by ReasonablySelenium** [AnonymousHacker1279/ImmersiveWeapons#39]
**Describe the bug**
I cannot use the copper ore in this mod in Tinker's Construct's Machines, including the smeltery.

**To Reproduce**
1. Mine Copper Ore from the mod.
2. Attempt to place the ore in the Multiblock Smeltery or the Seared Heater.

**Expected behavior**
The copper ore should be detected by the smeltery and be turned into Molten Copper.

**Screenshots**
![Image of Copper Ore not being detected by Tinker's Construct](https://i.imgur.com/4FVr9Pt.png)

**Setup**
 - Forge Version: 36.2
 - Immersive Weapons Version: 1.4.0
 - [My Mods List](https://gist.githubusercontent.com/ReasonablySelenium/404b9fd7f4b1dbf6b56bbf17b91f46d5/raw/033722095ef715e4cc5538c1f4608f8d2a5941dd/gistfile0.txt)
- [latest.log](https://gist.githubusercontent.com/ReasonablySelenium/ddeb3b416b67aa77f4252c57618c2437/raw/b6b365d40b02a8ebae949a683f0e1359b351f17d/problem.log)

**Comment by AnonymousHacker1279** [comment]
This seems to be a simple case of missing tags. I'm currently testing a patch for this and will update you soon.

**Comment by AnonymousHacker1279** [comment]
The v1.4.1 release should fix this (it does in my testing). Please let me know if the issue persists.
