### ISSUE TITLE
[BUG] Causes WAILA to crash on startup

### ISSUE THREAD

**Issue by imagelesskink** [AnonymousHacker1279/ImmersiveWeapons#48]
**Describe the bug**
Version 1.8.4 causes WAILA-based mods to crash on startup. Tested with both Jade and WTHIT.

**To Reproduce**
Install the latest version with a WAILA-based mod and try to start the game

**Expected behavior**
Ability to play Minecraft.

**Screenshots**

**Setup**
 - Forge Version: 37.0.51
 - Immersive Weapons Version: 1.8.4
 - Jade/WTHIT + a whole bunch of others
- Debug and latest logs (saves/logs folder in your .minecraft directory):
[latest.log](https://github.com/AnonymousHacker1279/ImmersiveWeapons/files/7102157/latest.log)
[debug.log](https://github.com/AnonymousHacker1279/ImmersiveWeapons/files/7102158/debug.log)
[crash-2021-09-02_18.32.45-fml.txt](https://github.com/AnonymousHacker1279/ImmersiveWeapons/files/7102160/crash-2021-09-02_18.32.45-fml.txt)

**Additional context**

**Comment by AnonymousHacker1279** [comment]
That's odd. I tested a user installation with IW and WTHIT, both of which were the latest version. I also don't see anything in the logs specifically mentioning IW. The error is related to a class being loaded that doesn't exist. 

In your log, I see Jade mentioned. I haven't tested with Jade yet, so I'll do that soon. Could you upload a crash log with WTHIT?

**Comment by AnonymousHacker1279** [comment]
Alright, just tested with Jade. It crashes with the same NoClassDefFoundError. Will look into this. Since it seems to be an issue of Jade not having the ``IBlockComponentProvider`` class that WTHIT has, I'll probably add a configuration option to disable the plugin.

**Comment by AnonymousHacker1279** [comment]
This should be fixed in the [v1.8.5](https://github.com/AnonymousHacker1279/ImmersiveWeapons/releases/tag/v1.8.5) release. Please let me know if the issue persists.
