### ISSUE TITLE
Crash when teleporting to the custom dimension

### ISSUE THREAD

**Issue by Catomax262** [AnonymousHacker1279/ImmersiveWeapons#76]
https://crashy.net/rBgWecBSW27d2n3762eG - crash log

**Comment by AnonymousHacker1279** [comment]
> tl_skin_cape_forge_1.18_1.18.2-1.25.jar | TLSkinCape | tlskincape | 1.25

You appear to have a mod relating to TLauncher installed, a common pirating client; I will not help users who pirate the game. Please provide proof of purchase.

**Comment by Catomax262** [comment]
Pfft. Whatever. Pirated or unpirated an issue is still an issue.

**Comment by AnonymousHacker1279** [comment]
I cannot reproduce this in my own environment, and there have been no reported issues from other users who are in my Discord server.

Anyways pirating is against EULA and I cannot support you for legal reasons.
