### ISSUE TITLE
Wandering Warriors have incorrect spawning conditions for 1.18 and above

### ISSUE THREAD

**Issue by alisolarflare** [AnonymousHacker1279/ImmersiveWeapons#79]
After 1.18, the caves and cliffs update, all hostile mobs spawn at light level 0.

Wandering warriors and hans the mighty however, spawn at light level 7. This leads to immersive weapons mobs being the only ones spawning, in well-lit areas at night. 

![image](https://user-images.githubusercontent.com/18705807/198909221-5b1dd00c-6113-4aa7-b938-1ac0066a5e7e.png)

**Comment by alisolarflare** [comment]
Release Date: 6/13/2022
File Name: ImmersiveWeapons-1.18.2-1.17.0.jar
File Type: Release
Game Version: 1.18.2

**Comment by AnonymousHacker1279** [comment]
I'll take a look at it within the next few days. I definitely didn't modify the light conditions to match the new vanilla spawns. It should be an easy fix.

Thanks for the report!

**Comment by AnonymousHacker1279** [comment]
This is now fixed in the latest commit on `master`, for 1.19. The release should be available shortly in the repository and on CurseForge.

I'll get to 1.18.2 soon.

**Comment by alisolarflare** [comment]
Thank you! :D

**Comment by AnonymousHacker1279** [comment]
There is now a release for 1.18.2 that has the bugfix included. Sorry it took so long!
