### ISSUE TITLE
Regarding the production of language files

### ISSUE THREAD

**Issue by shenyx110** [AnonymousHacker1279/ImmersiveWeapons#89]
关于语言文件制作 我着手汉化语言文件请问应该如何提交简体中文语言包
Regarding the production of language files, I started to localize language files. How should I submit the simplified Chinese language package?

**Comment by AnonymousHacker1279** [comment]
You will need to fork this repository, then commit or upload your language file to `/src/main/resources/assets/immersiveweapons/lang`. After that you can come back to this repository and make a new pull request to merge your fork into this repository. Let me know if you need more information.

**Comment by shenyx110** [comment]
Sorry, I don't know why the language file I made can't be recognized correctly. I have Chineseized many modules before. This is the first time I've seen this situation. I want to submit it directly to you zh_cn.json
[IW.zip](https://github.com/AnonymousHacker1279/ImmersiveWeapons/files/11503468/IW.zip)

**Comment by shenyx110** [comment]
key bug fix 
[IW.zip](https://github.com/AnonymousHacker1279/ImmersiveWeapons/files/11504800/IW.zip)

**Comment by AnonymousHacker1279** [comment]
Thanks! I'll merge it into an upcoming release when I get time from school. Hopefully within the next few days. I'll comment back here when it's ready.

**Comment by AnonymousHacker1279** [comment]
Version v1.22.1 has been released which includes the new translation file. Thank you so much for the contribution! I appreciate it.
