### ISSUE TITLE
Crashing During World Creation mc 1.19.4

### ISSUE THREAD

**Issue by Devilswarchild** [AnonymousHacker1279/ImmersiveWeapons#93]
for whatever reason this mod is causing a massive issue when creating a new world. upon loading into the new after creation, the screen stays black whilst hearing the game sounds and then just as soon as you think its going to color in, the world closes with the message "server closed" have tested this repeatedly to make sure it wasnt a fluke and as soon as I disabled immersive weapons the issue disappeared.

mc 1.19.4
forge 45.0.1
ImmersiveWeapons-1.19.4-1.23.0.jar

below I will list all the logs that were generated during the issue for your convenience.

[debug](https://mclo.gs/ExIiDtD)

[crash report](https://mclo.gs/XaGQy0c)

[client log](https://mclo.gs/47GXv7l)

[launcher_log](https://mclo.gs/6JIM4de)

**Comment by AnonymousHacker1279** [comment]
Looks like its crashing while listening to a Forge event. I'll take a look at it soon, thankfully it doesn't seem too complicated to fix. Thanks for the report!

**Comment by AnonymousHacker1279** [comment]
A new release, v1.23.1, has been released which should fix the issue. https://curseforge.com/minecraft/mc-mods/immersive-weapons/files/4595962

It may take a little while for the CurseForge release to become public, but you can download it now from this repository.

**Comment by AnonymousHacker1279** [comment]
No problem! Glad the issue is fixed.
